name: Deploy to Staging

on:
  push:
    branches: [staging]

env:
  IMAGE_NAME: sosurbano-api-staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image (staging)
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Deploy to Azure (Staging)
        uses: azure/webapps-deploy@v2
        with:
          app-name: apisosurbano-staging-aegteff6h4cgc6f0
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_STAGING }}
          images: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
